default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
  username: masatoshi
  password:

development:
  <<: *default
  database: rails_p2p_development

test:
  <<: *default
  database: rails_p2p_test

production:
  <<: *default
  database: rails_p2p_production
  username:
  password:
